volumes:
  pistade:
    external: true
  enhance:
    external: true

services:
  pistade:
    container_name: pistade
    image: pistade
    build: .
    volumes:
      - pistade:/root/.cache
      - enhance:/opt/conda/lib/python3.10/site-packages/resemble_enhance/model_repo
      - ./data:/data
      - ./dump:/dump
    entrypoint: python /data/run.py --synthesize
    devices:
      - "/dev/snd:/dev/snd"
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all