volumes:
  forge:
    external: true

services:
  forge:
    image: forge
    build: .
    ports:
      - 7860:7860
    volumes:
      - ./Forge:/forge
      - forge:/root/.cache
    entrypoint: /forge/webui.sh -f --server-name 0.0.0.0 --cuda-stream --cuda-malloc --pin-shared-memory
    healthcheck:
      test: curl http://localhost:7860
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all