volumes:
  comfy:
    external: true

services:
  comfy:
    image: comfy
    build: .
    ports:
      - 8188:8188
      - 7860:7860
      - 9000:9000
    volumes:
      - ./input:/input
      - ./Comfy:/comfy
      - comfy:/root/.cache
    init: true
    healthcheck:
      test: curl --fail http://localhost:8188 && curl --fail http://localhost:9000/status
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
