volumes:
  comfy:
    external: true

services:
  comfy:
    image: comfy
    build: .
    ports:
      - 8188:8188
      - 7860:7860
      - 9000:9000
    volumes:
      - ./input:/input
      - ./Comfy:/comfy
      - comfy:/root/.cache
    init: true
    healthcheck:
      test: curl --fail http://localhost:8188 && curl --fail http://localhost:9000/status
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  zoomy:
    image: zoomy
    build: ./Zoomy
    ports:
      - 127.0.0.1:7861:7861
    volumes:
      - ./Comfy/output:/comfy/output
    environment:
      ZOOMY_COMFY_ADDRESS: http://comfy:8188
      ZOOMY_OUTPUT_DIRECTORY: /comfy/output
    init: true
    healthcheck:
      test: curl --fail http://localhost:7861/
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
