volumes:
  ollama:
    external: true
  web:
    external: true

services:
  web:
    image: ghcr.io/open-webui/open-webui:ollama
    restart: always
    ports:
      - 3000:8080
    volumes:
      - ollama:/root/.ollama
      - web:/app/backend/data
    healthcheck:
      test: ollama --version
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
