volumes:
  ollama:
    external: true

services:
  ollama:
    image: ollama
    build: .
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all